// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/tokenservice_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/tokenservice_interface.go -destination=internal/auth/mocks/mock_tokenservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// InvalidateRefreshToken mocks base method.
func (m *MockTokenIssuer) InvalidateRefreshToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRefreshToken indicates an expected call of InvalidateRefreshToken.
func (mr *MockTokenIssuerMockRecorder) InvalidateRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRefreshToken", reflect.TypeOf((*MockTokenIssuer)(nil).InvalidateRefreshToken), ctx, token)
}

// IssueAccessToken mocks base method.
func (m *MockTokenIssuer) IssueAccessToken(userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockTokenIssuerMockRecorder) IssueAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockTokenIssuer)(nil).IssueAccessToken), userID)
}

// IssueRefreshToken mocks base method.
func (m *MockTokenIssuer) IssueRefreshToken(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRefreshToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRefreshToken indicates an expected call of IssueRefreshToken.
func (mr *MockTokenIssuerMockRecorder) IssueRefreshToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefreshToken", reflect.TypeOf((*MockTokenIssuer)(nil).IssueRefreshToken), ctx, userID)
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenIssuer) ValidateRefreshToken(ctx context.Context, opaque string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", ctx, opaque)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenIssuerMockRecorder) ValidateRefreshToken(ctx, opaque any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenIssuer)(nil).ValidateRefreshToken), ctx, opaque)
}
