// Code generated by MockGen. DO NOT EDIT.
// Source: internal/post/feed_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/post/feed_repository.go -destination=internal/post/mocks/mock_feed_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	post "github.com/anthonymartz17/thinkmartz_backend/internal/post"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// AddToFeed mocks base method.
func (m *MockFeedRepository) AddToFeed(ctx context.Context, p post.Post, followerIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFeed", ctx, p, followerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToFeed indicates an expected call of AddToFeed.
func (mr *MockFeedRepositoryMockRecorder) AddToFeed(ctx, p, followerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFeed", reflect.TypeOf((*MockFeedRepository)(nil).AddToFeed), ctx, p, followerIDs)
}
